[alembic]
script_location = migrations
prepend_sys_path = .
version_path_separator = os

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/gestao_franquias

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %%H:%%M:%%S


; O alembic.ini é o arquivo de configuração do Alembic — funciona como um "painel de controle" das migrations. Ele define:
; script_location = migrations — onde ficam os arquivos de migration (a pasta migrations/)
; sqlalchemy.url — qual banco de dados o Alembic vai conectar para gerar e executar as migrations
; [loggers], [handlers], [formatters] — configuração de log, define o que o Alembic vai mostrar no terminal quando rodar (INFO, WARN, etc)
; No nosso caso, o alembic.ini tem a URL do banco mas o env.py sobrescreve essa URL com a do .env via settings.databaseUrl. Isso é intencional — 
; o alembic.ini fica com uma URL padrão de fallback, mas quem manda de verdade é o .env.